# Advanced HMAY-TSF Configuration File
# Complete implementation for achieving 99.2%+ accuracy, precision, recall, and F1 score

# Model Configuration
model:
  size: 's'  # n, s, m, l, x (nano, small, medium, large, extra-large)
  num_classes: 11
  pretrained: true
  freeze_backbone: true  # Freeze backbone initially for fine-tuning

# Advanced Training Configuration
training:
  epochs: 200  # Increased epochs for better convergence
  batch_size: 8  # Reduced for stability and better gradient updates
  img_size: 640
  device: 'auto'  # auto, cpu, cuda, 0, 1, etc.
  workers: 4  # Reduced for stability
  patience: 100  # Increased patience for better convergence
  
  # Advanced Optimization
  optimizer: 'AdamW'
  lr0: 0.001
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 10  # Increased warmup
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  
  # Advanced loss weights for better performance
  box_loss_weight: 7.5
  cls_loss_weight: 0.5
  dfl_loss_weight: 1.5
  
  # Advanced learning rate scheduling
  lr_scheduler: 'cosine_annealing_warm_restarts'
  lr_scheduler_params:
    T_0: 10
    T_mult: 2
    eta_min: 0.00001

# Advanced Data Augmentation with Curriculum Learning
augmentation:
  # HSV augmentation
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  
  # Geometric augmentation
  degrees: 0.373
  translate: 0.245
  scale: 0.898
  shear: 0.602
  perspective: 0.0
  flipud: 0.00856
  fliplr: 0.5
  
  # Advanced augmentation
  mosaic: 1.0
  mixup: 0.243
  copy_paste: 0.362
  
  # Advanced augmentations for better generalization
  random_resized_crop:
    enabled: true
    scale: [0.8, 1.0]
    ratio: [0.8, 1.2]
    p: 0.8
  
  color_augmentation:
    brightness_contrast: [0.3, 0.3]
    gamma: [80, 120]
    clahe: [2.0, 8, 8]
    hue_saturation: [20, 30, 20]
    rgb_shift: [20, 20, 20]
    channel_shuffle: true
  
  noise_blur:
    gauss_noise: [10.0, 50.0]
    gaussian_blur: [3, 7]
    motion_blur: 7
    median_blur: 5
  
  weather_effects:
    random_rain: [-10, 10, 20, 1, 200]
    random_fog: [0.1, 0.3]
    random_sunflare: [0, 0, 1, 0.5, 0, 1]
  
  advanced_augmentation:
    coarse_dropout: [8, 32, 32, 1]
    grid_distortion: [5, 0.3]
    optical_distortion: [0.2, 0.15]
  
  # Curriculum Learning Stages
  curriculum_learning:
    enabled: true
    stages:
      - epochs: 50
        difficulty: 'easy'
        augmentation_strength: 0.3
      - epochs: 100
        difficulty: 'medium'
        augmentation_strength: 0.6
      - epochs: 150
        difficulty: 'hard'
        augmentation_strength: 0.8
      - epochs: 200
        difficulty: 'expert'
        augmentation_strength: 1.0

# Dataset Configuration
dataset:
  path: './dataset'
  train: 'images/train'
  val: 'images/val'
  test: 'images/test'
  cache: false  # Set to true if you have enough RAM
  
  # Advanced data loading
  prefetch_factor: 2
  persistent_workers: true
  pin_memory: true

# Advanced Evaluation Configuration
evaluation:
  conf_threshold: 0.25
  iou_threshold: 0.45
  max_detections: 300
  
  # Custom metrics
  small_object_threshold: 0.05  # Area threshold for small objects
  occlusion_thresholds:
    light: 0.05
    medium: 0.1
  
  # Advanced evaluation settings
  save_json: true
  save_txt: true
  save_conf: true
  plots: true

# Performance Targets (Advanced - 99.2%+)
targets:
  map50: 0.992      # mAP@0.5 - Target 99.2%
  map50_95: 0.95    # mAP@0.5:0.95 - Target 95%
  precision: 0.992  # Target 99.2%
  recall: 0.992     # Target 99.2%
  f1_score: 0.992   # Target 99.2%
  accuracy: 0.992   # Target 99.2%
  fps: 40           # Frames per second
  small_object_recall: 0.985

# Hardware Configuration
hardware:
  # Memory optimization
  amp: true        # Automatic mixed precision
  cache_images: false
  
  # For edge deployment
  quantization: false
  tensorrt: false
  
  # Advanced memory management
  gradient_accumulation_steps: 1
  max_grad_norm: 10.0

# Paths
paths:
  weights_dir: './runs/train'
  results_dir: './runs/predict'
  logs_dir: './logs'
  checkpoints_dir: './checkpoints'

# Advanced Methodology Implementation Flags
methodology:
  use_conditional_conv: true
  use_temporal_fusion: true
  use_super_resolution: true  # Enabled for better small object detection
  use_active_learning: false   # Can be enabled for large datasets
  use_bifpn: true
  use_spp_csp: true
  use_focal_loss: true
  use_iou_loss: true
  use_enhanced_augmentation: true
  use_curriculum_learning: true
  use_mixed_precision: true

# Advanced Training Features
advanced:
  # Loss functions
  focal_loss:
    alpha: 1.0
    gamma: 2.0
    label_smoothing: 0.1
  
  iou_loss:
    reduction: 'mean'
    iou_type: 'ciou'  # Complete IoU loss
  
  # Regularization
  dropout: 0.1
  label_smoothing: 0.1
  
  # Advanced techniques
  mixup_alpha: 0.2
  cutmix_alpha: 1.0
  auto_augment: true
  
  # Model ensemble
  ensemble_size: 1
  test_time_augmentation: true
  
  # Advanced optimization
  lookahead: false
  ralamb: false
  gradient_centralization: true
  
  # Advanced scheduling
  cosine_lr: true
  close_mosaic: 10

# Monitoring and Logging
monitoring:
  # Metrics tracking
  track_metrics: true
  save_plots: true
  save_confusion_matrix: true
  
  # Advanced logging
  log_interval: 10
  save_interval: 5
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 100
    min_delta: 0.001
    monitor: 'val_f1'
    mode: 'max'
  
  # Model checkpointing
  checkpointing:
    save_best: true
    save_last: true
    save_top_k: 3
    monitor: 'val_f1'
    mode: 'max'

# Post-processing
post_processing:
  # NMS settings
  nms_iou_threshold: 0.45
  nms_score_threshold: 0.25
  
  # Advanced filtering
  min_box_size: 1
  max_box_size: 1000
  
  # Confidence calibration
  temperature_scaling: false
  temperature: 1.0
  
  # Ensemble post-processing
  weighted_boxes_fusion: false
  wbf_iou_threshold: 0.55
  wbf_skip_box_threshold: 0.4

# Advanced Model Architecture
architecture:
  # Conditional Convolutions
  conditional_conv:
    num_experts: 16
    reduction: 8
    use_residual: true
  
  # Temporal-Spatial Fusion
  temporal_fusion:
    seq_len: 8
    num_heads: 16
    use_3d_conv: true
    use_attention: true
  
  # Super-Resolution
  super_resolution:
    scale_factor: 2
    num_blocks: 12
    use_attention: true
  
  # BiFPN
  bifpn:
    num_layers: 4
    use_attention: true
  
  # SPP-CSP
  spp_csp:
    use_cbam: true
    attention_reduction: 16 