# Advanced HMAY-TSF Configuration with YOLOv11
# Target: Fine-tuning approach with YOLOv11 and extra trainable layers

# Model Configuration
model:
  version: 'yolov11'  # Use YOLOv11 instead of YOLOv8
  size: 's'  # Model size (n, s, m, l, x)
  num_classes: 11
  use_yolov11: true
  fallback_to_yolov8: true  # Fallback to YOLOv8 if YOLOv11 not available

# Fine-tuning Configuration
fine_tuning:
  enabled: true
  freeze_backbone: true
  freeze_ratio: 0.7  # Freeze 70% of YOLO layers
  train_detection_head: true
  train_extra_layers: true
  
  # Extra trainable layers
  conditional_conv: true
  temporal_spatial_fusion: true
  super_resolution: true
  bifpn: true
  spp_csp: true

# Training Configuration
training:
  epochs: 10  # Fine-tuning epochs
  batch_size: 8
  img_size: 640
  warmup_epochs: 3  # Longer warmup for fine-tuning
  patience: 10  # Reduced for fine-tuning
  
  # Fine-tuning optimization
  optimizer: 'AdamW'
  lr0: 0.0001  # Lower learning rate for fine-tuning
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005  # Lower weight decay for fine-tuning
  
  # Fine-tuning loss weights
  box: 7.5
  cls: 0.5
  dfl: 1.5
  
  # Fine-tuning learning rate scheduling
  lr_scheduler: 'cosine_annealing_warm_restarts'
  lr_scheduler_params:
    T_0: 10
    T_mult: 2
    eta_min: 0.00001

# Fine-tuning Data Augmentation (less aggressive)
augmentation:
  # HSV augmentation
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  
  # Geometric augmentation (minimal for fine-tuning)
  degrees: 0.0  # No rotation for fine-tuning
  translate: 0.1  # Minimal translation
  scale: 0.5  # Minimal scaling
  shear: 0.0  # No shearing
  perspective: 0.0  # No perspective
  flipud: 0.0  # No vertical flip
  fliplr: 0.5  # Keep horizontal flip
  
  # Fine-tuning augmentation (less aggressive)
  mosaic: 0.0  # No mosaic for fine-tuning
  mixup: 0.0  # No mixup for fine-tuning
  copy_paste: 0.0  # No copy-paste for fine-tuning
  
  # Advanced augmentations for fine-tuning
  random_resized_crop:
    enabled: false  # Disabled for fine-tuning
    scale: [0.8, 1.0]
    ratio: [0.8, 1.2]
    p: 0.8
  
  color_augmentation:
    brightness_contrast: [0.1, 0.1]  # Reduced for fine-tuning
    gamma: [90, 110]  # Reduced for fine-tuning
    clahe: [2.0, 8, 8]
    hue_saturation: [10, 15, 10]  # Reduced for fine-tuning
    rgb_shift: [10, 10, 10]  # Reduced for fine-tuning
    channel_shuffle: false  # Disabled for fine-tuning
  
  noise_blur:
    gauss_noise: [5.0, 25.0]  # Reduced for fine-tuning
    gaussian_blur: [3, 5]  # Reduced for fine-tuning
    motion_blur: 5  # Reduced for fine-tuning
    median_blur: 3  # Reduced for fine-tuning
  
  weather_effects:
    random_rain: [0, 0, 0, 0, 0]  # Disabled for fine-tuning
    random_fog: [0, 0]  # Disabled for fine-tuning
    random_sunflare: [0, 0, 0, 0, 0, 0]  # Disabled for fine-tuning
  
  advanced_augmentation:
    coarse_dropout: [0, 0, 0, 0]  # Disabled for fine-tuning
    grid_distortion: [0, 0]  # Disabled for fine-tuning
    optical_distortion: [0, 0]  # Disabled for fine-tuning
  
  # Curriculum Learning Stages (simplified for fine-tuning)
  curriculum_learning:
    enabled: false  # Disabled for fine-tuning
    stages:
      - epochs: 50
        difficulty: 'easy'
        augmentation_strength: 0.3
      - epochs: 100
        difficulty: 'medium'
        augmentation_strength: 0.6
      - epochs: 150
        difficulty: 'hard'
        augmentation_strength: 0.8
      - epochs: 200
        difficulty: 'expert'
        augmentation_strength: 1.0

# Dataset Configuration
dataset:
  path: './dataset'
  train: 'images/train'
  val: 'images/val'
  test: 'images/test'
  cache: false  # Set to true if you have enough RAM
  
  # Advanced data loading
  prefetch_factor: 2
  persistent_workers: true
  pin_memory: true

# Advanced Evaluation Configuration
evaluation:
  conf_threshold: 0.25
  iou_threshold: 0.45
  max_detections: 300
  
  # Custom metrics
  small_object_threshold: 0.05  # Area threshold for small objects
  occlusion_thresholds:
    light: 0.05
    medium: 0.1
  
  # Advanced evaluation settings
  save_json: true
  save_txt: true
  save_conf: true
  plots: true

# Performance Targets (Realistic - 85%+)
targets:
  map50: 0.85      # mAP@0.5 - Realistic target
  map50_95: 0.70   # mAP@0.5:0.95 - Realistic target
  precision: 0.85  # Realistic target
  recall: 0.85     # Realistic target
  f1_score: 0.85   # Realistic target
  accuracy: 0.85   # Realistic target
  fps: 30          # Realistic FPS target
  small_object_recall: 0.80  # Realistic target

# Hardware Configuration
hardware:
  # Memory optimization
  amp: true        # Automatic mixed precision
  cache_images: false
  
  # For edge deployment
  quantization: false
  tensorrt: false
  
  # Advanced memory management
  gradient_accumulation_steps: 1
  max_grad_norm: 10.0

# Paths
paths:
  weights_dir: './runs/train'
  results_dir: './runs/predict'
  logs_dir: './logs'
  checkpoints_dir: './checkpoints'

# Advanced Methodology Implementation Flags
methodology:
  use_conditional_conv: true
  use_temporal_fusion: true
  use_super_resolution: true  # Enabled for better small object detection
  use_active_learning: false   # Can be enabled for large datasets
  use_bifpn: true
  use_spp_csp: true
  use_focal_loss: true
  use_iou_loss: true
  use_enhanced_augmentation: true
  use_curriculum_learning: true
  use_mixed_precision: true

# Advanced Training Features
advanced:
  # Loss functions
  focal_loss:
    alpha: 1.0
    gamma: 2.0
    label_smoothing: 0.1
  
  iou_loss:
    reduction: 'mean'
    iou_type: 'ciou'  # Complete IoU loss
  
  # Regularization
  dropout: 0.1
  label_smoothing: 0.1
  
  # Advanced techniques
  mixup_alpha: 0.2
  cutmix_alpha: 1.0
  auto_augment: true
  
  # Model ensemble
  ensemble_size: 1
  test_time_augmentation: true
  
  # Advanced optimization
  lookahead: false
  ralamb: false
  gradient_centralization: true
  
  # Advanced scheduling
  cosine_lr: true
  close_mosaic: 10

# Monitoring and Logging
monitoring:
  # Metrics tracking
  track_metrics: true
  save_plots: true
  save_confusion_matrix: true
  
  # Advanced logging
  log_interval: 10
  save_interval: 5
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 100
    min_delta: 0.001
    monitor: 'val_f1'
    mode: 'max'
  
  # Model checkpointing
  checkpointing:
    save_best: true
    save_last: true
    save_top_k: 3
    monitor: 'val_f1'
    mode: 'max'

# Post-processing
post_processing:
  # NMS settings
  nms_iou_threshold: 0.45
  nms_score_threshold: 0.25
  
  # Advanced filtering
  min_box_size: 1
  max_box_size: 1000
  
  # Confidence calibration
  temperature_scaling: false
  temperature: 1.0
  
  # Ensemble post-processing
  weighted_boxes_fusion: false
  wbf_iou_threshold: 0.55
  wbf_skip_box_threshold: 0.4

# Advanced Model Architecture
architecture:
  # Conditional Convolutions
  conditional_conv:
    num_experts: 16
    reduction: 8
    use_residual: true
  
  # Temporal-Spatial Fusion
  temporal_fusion:
    seq_len: 8
    num_heads: 16
    use_3d_conv: true
    use_attention: true
  
  # Super-Resolution
  super_resolution:
    scale_factor: 2
    num_blocks: 12
    use_attention: true
  
  # BiFPN
  bifpn:
    num_layers: 4
    use_attention: true
  
  # SPP-CSP
  spp_csp:
    use_cbam: true
    attention_reduction: 16 